# Generated by Django 5.1 on 2024-09-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("price", models.IntegerField()),
                ("genre", models.CharField(max_length=100)),
                ("summary", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
